version: '2'
services:
  mongodb:
    image: mangoraft/mongodb-arm
    restart: always
    command: bash -c "mongod --repair && mongod"
    volumes:
      - mongodb_volume:/data/db
      - mongodb_config:/data/configdb

  bot:
    build: ./
    restart: always
    volumes:
      - ./:/app
    links:
      - mongodb
    depends_on:
      - mongodb
    command: python main.py

  webserver:
    build: ./
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./:/app
    links:
      - mongodb
    depends_on:
      - mongodb
    command: gunicorn --workers 1 --bind 0.0.0.0:1883 wsgi:app

volumes:
   mongodb_volume:
   mongodb_config:
