USER_COMMAND_DATA = 'Data'
USER_COMMAND_CO2 = 'CO2'
USER_COMMAND_1_HOUR = '1h'
USER_COMMAND_3_HOUR = '3h'
USER_COMMAND_24_HOUR = '24h'

USER_COMMAND_TEMPERATURE = 'Temperature'
USER_COMMAND_HUMIDITY = 'Humidity'

USER_COMMAND_BACK = '⬅️Back'
