USER_COMMAND_DATA = 'Status'
USER_COMMAND_CO2 = 'CO₂'
USER_COMMAND_1_HOUR = '1h'
USER_COMMAND_3_HOUR = '3h'
USER_COMMAND_24_HOUR = '24h'

USER_COMMAND_TEMPERATURE = 'Температура'
USER_COMMAND_HUMIDITY = 'Влажность'

USER_COMMAND_BACK = '⬅️Back'
